In [1]:
import numpy as np
import itertools
from numpy.linalg import matrix_rank
from src.data.synthetic_data import SyntheticDataGenerator

# Example parition
# # Species = [S1, S2, S3, S4, S5, S6, S7, S8, S9, S_out]
# # Inputs = [S1, S2, S5, S8]
# # Hidden = [S3, S4, S6, S7, S9]
# # Output = S_out
# All that matters in the number in each group, not the specific species labels which are equivalent up to change of names.

# Example reaction
# # S_0 + S_1 <=> S_2 + S_3
# # S_3 + S_4 <=> S_5 + S_6
# # S_6 + S_7 <=> S_8 + S_out

generator = SyntheticDataGenerator(
    number_of_nonoutput_species=9, 
    reaction_rate_ranges={'k_f': (0, 1.0), 'k_r': (0, 1.0)},
    initial_concentration_range = (1, 10)
    )  


In [2]:
generator.partitions[0]


Partition(inputs=['S_1'], hidden=['S_2', 'S_3', 'S_4', 'S_5', 'S_6', 'S_7', 'S_8', 'S_9'], output='S_out')

In [52]:
#%%timeit
seed = 42
partition = generator.partitions[0]
atomic_components = 7
max_components_per_species = 3
rank_target = None
for _ in range(3):
    A = generator.sample_composition_matrix(partition, atomic_components, max_components_per_species, rank_target, seed)
    display(A)
    print(f"Rank: {matrix_rank(A)}\n")
    seed += 1


array([[0, 2, 0, 3, 2, 2, 1, 2, 1, 1],
       [3, 0, 2, 0, 1, 0, 1, 0, 1, 2],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Rank: 6



array([[2, 1, 1, 0, 3, 1, 1, 1, 0, 1],
       [1, 0, 1, 3, 0, 0, 0, 2, 1, 1],
       [0, 1, 1, 0, 0, 0, 2, 0, 2, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Rank: 5



array([[2, 1, 3, 0, 2, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 2, 1, 0, 3, 2],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Rank: 6

